variable "name" {}
variable "vpc_id" {}
variable "vpc_subnet_ids" {}
variable "tags" {}
variable "instance_type" {}
variable "security_group_id" {}
variable "public_key" {}
variable "private_ip" {}
variable "upstream_ip" {}
